<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noimageindex"><title><?= esc($brand) ?> — Video Storage</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#edf3ff;font:16px/1.6 system-ui,sans-serif}a{color:inherit;text-decoration:none}.wrap{max-width:1160px;margin:auto;padding:0 28px}header{display:flex;justify-content:space-between;align-items:center;padding:28px 0;border-bottom:1px solid #253047}.brand{font-weight:750;letter-spacing:-.5px;display:flex;gap:12px;align-items:center}.logo{background:#abefcf;color:#092d22;border-radius:12px;padding:4px 13px;font-size:22px}.access{border:1px solid #43516a;padding:9px 18px;border-radius:8px;font-size:14px}.hero{display:grid;grid-template-columns:1.1fr 1fr;gap:70px;align-items:center;padding:100px 0 80px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:3px;color:#abefcf}h1{font-size:clamp(38px,5vw,65px);line-height:1.08;letter-spacing:-2px;margin:24px 0}p{color:#a7b4c9}.intro{max-width:480px;font-size:18px}.button{display:inline-block;background:#abefcf;color:#092d22;font-weight:700;padding:13px 23px;border-radius:9px;margin-top:20px}.preview{background:linear-gradient(135deg,#1d2d47,#111c30);border:1px solid #344560;border-radius:22px;padding:25px;box-shadow:0 30px 80px #0005;transform:rotate(2deg)}.preview-top{display:flex;justify-content:space-between;font-size:12px;color:#a7b4c9}.screen{height:220px;margin:24px 0;background:radial-gradient(ellipse at 30% 30%,#436476,transparent 70%),linear-gradient(140deg,#172840,#080f1c);border-radius:14px;display:grid;place-items:center}.play{width:68px;height:68px;display:grid;place-items:center;border:1px solid #ffffff40;border-radius:50%;background:#ffffff15;font-size:25px}.file{display:flex;align-items:center;gap:12px;background:#ffffff05;border:1px solid #ffffff0c;border-radius:10px;padding:12px;margin-top:9px;font-size:13px}.file small{margin-left:auto;color:#a7b4c9}.dot{color:#abefcf}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;border-top:1px solid #253047;padding:35px 0 65px}.features h2{font-size:18px}.features p{font-size:14px}.number{font:12px monospace;color:#abefcf}footer{padding:24px 0;border-top:1px solid #253047;color:#a7b4c9;font-size:12px;display:flex;justify-content:space-between}@media(max-width:760px){.hero{grid-template-columns:1fr;gap:35px;padding:55px 0}.preview{transform:none}.features{grid-template-columns:1fr;gap:8px}.wrap{padding:0 20px}.brand{max-width:65%;overflow-wrap:anywhere}footer{gap:20px}}
</style></head><body><div class="wrap">
<header><a class="brand" href="<?= site_url('/') ?>"><span class="logo" aria-hidden="true">▸</span><?= esc($brand) ?></a><a class="access" href="<?= site_url('/admin_login') ?>">Sign in ↗</a></header>
<main><section class="hero"><div><span class="eyebrow">Video storage & sharing</span><h1><?= esc($heading) ?></h1><p class="intro"><?= esc($intro) ?></p><a class="button" href="<?= site_url('/admin_login') ?>">Open your workspace →</a></div>
<div class="preview" aria-label="Illustration of a video library"><div class="preview-top"><span>YOUR VIDEO LIBRARY</span><span>•••</span></div><div class="screen"><span class="play" aria-hidden="true">▷</span></div><div class="file"><span class="dot">▣</span>Project highlights.mp4<small>VIDEO</small></div><div class="file"><span class="dot">▣</span>Creative collection.mp4<small>VIDEO</small></div></div></section>
<section class="features"><article><span class="number">01 / ORGANIZE</span><h2>A place for every video</h2><p>Keep titles, posters, and video links together in your library.</p></article><article><span class="number">02 / SHARE</span><h2>Ready to embed</h2><p>Use a dedicated player link to bring your videos to your website.</p></article><article><span class="number">03 / MANAGE</span><h2>Stay in control</h2><p>Manage your collection and monitor stream links from your workspace.</p></article></section></main>
<footer><span>© <?= date('Y') ?> <?= esc($brand) ?></span><span>Built around your video collection.</span></footer></div><?= view('partials/google_analytics', ['ga4Context'=>'public']) ?>
</body></html>
