const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage();await page.setContent(`<div id="secure-backups" data-url="/run" data-download="/download" data-token="token">
<select id="secure-scope"><option value="full">Full</option></select><select id="secure-destination"><option value="local">Local</option><option value="s3">S3</option></select><button data-secure-action="files">Backup</button>
<form id="secure-remote-s3" data-remote-provider="s3"><input name="endpoint" value="https://s3.example.com"><input name="secret_key" type="password" value="fixture"><button>Simpan</button></form>
<input id="secure-remote-reference"><button data-secure-action="remote-download">Unduh untuk Restore</button><form id="secure-upload"><input type="file" id="secure-file"><button>Upload</button></form><div id="secure-progress" hidden><span id="secure-spinner"></span><p id="secure-status"></p><div id="secure-bar"></div></div><table><tbody id="secure-list"></tbody></table>
<script type="application/json" id="secure-initial">[{"id":"a","name":"full.zip","kind":"full","size":1,"created_at":"2026-09-08T00:00:00Z"}]</script></div>`);
await page.evaluate(()=>{window.calls=[];window.fetch=async(url,{body})=>{const data=Object.fromEntries(body);window.calls.push(data);const entry={id:'a',name:'full.zip',kind:'full',size:1,created_at:'2026-09-08T00:00:00Z'};if(data.action==='remote-send')return {ok:false,json:async()=>({message:'S3 menolak upload',entries:[entry]})};return {ok:true,json:async()=>({message:'Selesai',entries:[entry]})};};});
await page.addScriptTag({path:'public/admin-assets/js/secure-backups.js'});
await page.locator('[data-secure-action="remote-send"]').click();assert.equal((await page.evaluate(()=>window.calls)).length,0);assert.match(await page.locator('#secure-status').textContent(),/Pilih FTP/);
await page.locator('#secure-remote-s3 button').click();await page.waitForFunction(()=>document.querySelector('#secure-remote-s3 input[type=password]').value==='');let calls=await page.evaluate(()=>window.calls);assert.equal(calls[0].action,'remote-save');assert.equal(calls[0].provider,'s3');assert.equal(calls[0].secret_key,'fixture');assert.equal(calls[0].token,'token');
await page.locator('#secure-destination').selectOption('s3');await page.locator('[data-secure-action="files"]').click();await page.waitForFunction(()=>window.calls.some(x=>x.action==='files'));calls=await page.evaluate(()=>window.calls);assert.equal(calls.at(-1).destination,'s3');assert.equal(calls.at(-1).scope,'full');
await page.locator('[data-secure-action="remote-send"]').click();await page.waitForFunction(()=>document.getElementById('secure-status').textContent==='S3 menolak upload');assert.match(await page.locator('#secure-list').textContent(),/full.zip/);assert.equal(await page.locator('[data-secure-action="remote-send"]').isEnabled(),true);
await page.locator('#secure-remote-reference').fill('backup.sql');await page.locator('[data-secure-action=remote-download]').click();await page.waitForFunction(()=>window.calls.some(x=>x.action==='remote-download'));calls=await page.evaluate(()=>window.calls);assert.equal(calls.at(-1).reference,'backup.sql');assert.equal(calls.at(-1).destination,'s3');assert.equal(calls.some(x=>x.action==='restore'),false);
console.log('PASS: remote settings submission, cleared secret inputs, explicit destination, full backup destination and retry after remote failure');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
